{
 "title": "Weather Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Wind",
   "type": "timeseries",
   "description": "Wind data from Bresser weather station",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT time, wind_avg_m_s from weather WHERE time >= 1752910064905 / 1000 and time < 1752996464905 / 1000",
     "rawQueryText": "SELECT time, wind_avg_m_s from weather WHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 12 },
   "targets": [
    {
     "queryText": "SELECT time, temperature_C from weather WHERE time >= 1752894143766 / 1000 and time < 1752937343766 / 1000",
     "rawQueryText": "SELECT time, temperature_C from weather WHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "description": "Rain",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 21 },
   "targets": [
    {
     "queryText": "SELECT time, rain_mm from weather WHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT time, rain_mm from weather WHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}